server:
  pathPrefix: HTTP_SERVER_PATH_PREFIX

aws:
  sqs:
    queueUrl: SQS_QUEUE_URL #https://sqs.eu-west-1.amazonaws.com/account-id/queue-name
  s3:
    bucketName: S3_BUCKET_NAME
    bucketPrefix: S3_BUCKET_PREFIX




